export const vehicleData = {
  "ABZO Motors": ["ABZO VS01"],
  "Ather Energy": ["450S", "450X", "Rizta S"],
  "Altigreen": ["Neev"],
  "Ashok Leyland": [
    "AVTR 55T EV",
    "Bada Dost i1 Electric",
    "Boss 1218 HB EV",
    "Boss 1219 EV",
    "Boss 14 HB EV",
    "Boss 14T EV",
    "Boss 19T EV",
    "Dost Electric",
    "IeV3",
    "IeV4",
    "IeV8",
    "Metrocity EV",
    "Metrodecker EV",
    "Optare Versa EV"
  ],
  "Bajaj Auto": ["Chetak Premium", "Chetak Urbane"],
  "EMotorad": ["Doodle V2", "T-Rex"],
  "Etrio": ["Touro Max+", "Touro Mini"],
  "Euler Motors": ["HiLoad EV"],
  "EVage": ["Model X"],
  "Firefox": ["Adventron", "Volante"],
  "Hero Lectro": ["C5X", "F2i", "H7Σ"],
  "Hero MotoCorp": ["Vida V1 Plus", "Vida V1 Pro"],
  "Hyundai": [
    "Creta Electric",
    "IONIQ 5",
    "IONIQ 6",
    "Kona Electric (2025 Facelift)",
    "Nexo"
  ],
  "Mahindra": [
    "BE 07",
    "BE 09",
    "BE 6",
    "BE Rall-E",
    "Thar EV",
    "Treo Plus",
    "Treo Yaari",
    "Treo Zor",
    "XEV 9e",
    "XUV 3XO EV",
    "XUV 900 Electric",
    "XUV e8",
    "XUV400 EV",
    "Zor Grand",
    "eKUV100",
    "eSupro Cargo Van"
  ],
  "Maruti Suzuki": [
    "Electric Baleno",
    "Electric Dzire",
    "Electric Fronx",
    "Electric Swift",
    "Electric WagonR",
    "eVX",
    "eVitara"
  ],
  "Montra": ["Electric Super Auto"],
  "Ninety One": ["E-Drago", "Meraki", "Meraki S7", "e-Tron"],
  "Nissan": [
    "Ariya",
    "Chill-Out Concept",
    "Hang-Out Concept",
    "Hyper Force Concept",
    "Hyper Punk Concept",
    "Hyper Tourer Concept",
    "Leaf",
    "Magnite EV",
    "Max-Out Concept",
    "Surf-Out Concept"
  ],
  "Oben Electric": ["Rorr"],
  "Ola Electric": ["Roadster Pro", "Roadster X", "S1", "S1 Pro"],
  "Olectra": ["Meghaetron Electric Tipper"],
  "Omega Seiki": ["M1KA 1.0", "Rage+", "Rage+ Frost", "Rage+ Rapid EV", "Rage+ Swap"],
  "Odysse": ["Evoqis"],
  "Piaggio": ["Ape E-City", "Ape E-Xtra FX"],
  "PURE EV": ["eTryst 350"],
  "Revolt Motors": ["RV 300", "RV 400"],
  "Royal Enfield": ["Upcoming Electric Model"],
  "Tata Motors": [
    "Ace EV",
    "Avinya",
    "Curvv EV",
    "Harrier EV",
    "Magic EV",
    "Nexon EV",
    "Punch EV",
    "Sierra EV",
    "Tigor EV",
    "Tiago EV",
    "Ultra T.7 Electric",
    "Ultra T.9 EV",
    "Prima E.28K"
  ],
  "Tork Motors": ["Kratos R", "Kratos X"],
  "TVS Motor": ["iQube", "iQube ST"],
  "Voltebyk": ["Eco 26T MTB", "Stylish Electric Bicycle"],
  "Yulu": ["Dex GR", "Miracle GR"],
  "Others": []
};
